project:
  type: website
  output-dir: docs

website:
  title: "Bradford Johnson"
  navbar:
    right:
      - text: "{{< fa address-card size=2x >}} About"
        href: index.qmd
      - resume.qmd
      - visuals.qmd
      - projects.qmd
  page-footer:
    right: "This website is built with ❤️ and [Quarto](https://quarto.org/)."
format:
  html:
    theme:
      - sandstone.scss
    mainfont: Roboto
    css: styles.css

editor: visual

