project:
  type: website
  resources:
    - robots.txt
  output-dir: docs

website:
  title: "Bradford Johnson"
  site-url: 'https://ford-johnson.com/'
  favicon: "images/favicon.png"
  navbar:
    pinned: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about/index.qmd
      - text: "Projects"
        href: projects/index.qmd
      - text: "Blog"
        href: blog/index.qmd
    right:
      - icon: linkedin
        href: https://linkedin.com/in/bradford-ford-johnson
      - icon: github
        href: https://github.com/bradfordjohnson
  page-footer:
    left: "Created by [Bradford Johnson](https://github.com/bradfordjohnson) © 2023"
    right: "This website is built with ❤️ and [Quarto](https://quarto.org/){target=\"_blank\"}."
smooth-scroll: true
format:
  html:
    include-in-header:
      - text: |
          <link rel="canonical" href="https://WWW.ford-johnson.com/">
    highlight-style: atom-one-light
    link-external-newwindow: true
    theme: "_variables.scss"
    css: styles.css

editor: visual