project:
  type: website
  output-dir: docs
website:
  title: "Bradford Johnson"
  navbar:
    pinned: true
    right:
      - text: "Home"
        href: index.qmd
        icon: house
      - href: projects.qmd
        icon: folder2
      - href: blog.qmd
        icon: newspaper
      - text: "About"
        href: about.qmd
        icon: file-person
  page-footer:
    left: "Created by [Bradford Johnson](https://github.com/bradfordjohnson) © 2023"
    right: "This website is built with ❤️ and [Quarto](https://quarto.org/){target=\"_blank\"}."
smooth-scroll: true
format:
  html:
    link-external-newwindow: true
    theme: [simplex] # removed scss file for now
    mainfont: Roboto
    css: styles.css
editor: visual