project:
  type: website
  output-dir: docs
  
website:
  title: "Bradford Johnson"
  favicon: favicon_io/favicon.ico
  navbar:
    pinned: true
    left:
      - icon: house
        text: "Home"
        href: index.qmd
      - icon: folder2
        href: projects.qmd
      - icon: newspaper
        href: blog.qmd
      - icon: file-person
        text: "About"
        href: about.qmd
    right: 
      - icon: code-square
        href: "https://github.com/bradfordjohnson/quarto-portfolio"
  page-footer:
    left: "Created by [Bradford Johnson](https://github.com/bradfordjohnson) © 2023"
    right: "This website is built with ❤️ and [Quarto](https://quarto.org/){target=\"_blank\"}."
smooth-scroll: true

format:
  html:
    link-external-newwindow: true
    theme: [simplex] # removed scss file for now
    mainfont: Roboto
    css: styles.css
editor: visual